#!/bin/bash
DEBIAN_FRONTEND=noninteractive
apt update
apt -o DPkg::Options::=--force-confdef install -y wget zsh tmux
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true

cd ~
tmux kill-server
git clone --single-branch https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf

cd /app
cp .devcontainer/.tmux.conf ~/.tmux.conf.local
make setup-dev
