name: Build

on: push

permissions:
  contents: write
  packages: write

jobs:

  build:
    uses: opvance/actions/.github/workflows/test-and-docs.yml@v1
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BADGES_TOKEN: ${{ secrets.PAT_BADGES }}

  ghcr:
    uses: opvance/actions/.github/workflows/build-image-and-push-to-ghcr.yml@v1
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      image_name: ${{ github.event.repository.name }}
